### ISSUE TITLE
Opening explorer API seems to not be parsing query params properly

### ISSUE THREAD

**Issue by Camsbury** [lichess-org/api#253] opened 2023-05-13 02:02 UTC
`curl https://explorer.lichess.ovh/masters\?moves\=30`
gives
`Failed to deserialize query string: invalid type: string "30", expected usize`

**Comment by niklasf** [comment] 2023-05-13 05:35
fixed via 511c594e788b81e0c045153b2762612f9c48a414. needs investigation for the root cause.

**Comment by niklasf** [comment] 2023-05-13 05:43
ah, it's  https://github.com/nox/serde_urlencoded/issues/33 / https://docs.rs/serde_qs/0.12.0/serde_qs/index.html#flatten-workaround

**Closed by niklasf** 2023-05-13 05:43 UTC
Labels: bug

**Comment by Camsbury** [comment] 2023-05-13 11:47
Thanks!
